#############################################################################
# Fake docker file for testing purposes
# Mock for building boost devnet images
#############################################################################
FROM alpine:3.16 as lotus-test

WORKDIR /app
RUN echo "echo Fake Lotus container" > entrypoint.sh && chmod +x entrypoint.sh
RUN cp entrypoint.sh /usr/local/bin/lotus && \
    cp entrypoint.sh /usr/local/bin/lotus-miner

ENTRYPOINT ["./entrypoint.sh"]
